version: '3.8'
services:
  bot:
    build: .
    ports:
      - "8080:8080"
    secrets:
      - bot_secret

  db:
    image: "mongo"
    secrets:
      - bot_secret


secrets:
  bot_secret:
    file: "./.config.json"